DROP TABLE if exists public.geoclass;
DROP TABLE if exists public.sections;

CREATE TABLE public.sections
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sections_pkey PRIMARY KEY (name)
);

CREATE TABLE public.geoclass
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255)  NOT NULL,
    code character varying(255)  NOT NULL,
    section_name character varying(255)  NOT NULL,
    CONSTRAINT geoclass_pkey PRIMARY KEY (id),
    CONSTRAINT geo_sections_fk FOREIGN KEY (section_name)
        REFERENCES public.sections (name) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

